services:
  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
  
  python-app:
    build: ./python-app
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/html/nginx.html  # This will copy nginx.html to NGINX's root directory
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
      - python-app
